### ISSUE TITLE
Make it more clear that you need to add a custom feature tag

### ISSUE THREAD

**Issue by Meantub** [JDare/GodotSteamHL#1]
The README doesn't include that when exporting your project you need to add a custom feature `steam` in the export menu. I was scratching my head for a while trying to figure out why Steam wasn't being initialized.

**Comment by JDare** [comment]
Thanks for the heads up. I assumed most people would be running their own SteamInit with custom logic, so I completely forgot about that. I've added it to the main docs under the setup and autoloads.
