### ISSUE TITLE
Packets can get queued up and cause a client to be behind by a fixed number of packets

### ISSUE THREAD

**Issue by mtaubert** [JDare/GodotSteamHL#2]
When sending lots of packets from different clients at once the queue of reliable packets can stack up since steam_network.gd only reads one every _process call. Can be fixed by calling _read_p2p_packet() until there is no more packet to read that frame.

**Comment by mtaubert** [comment]
```
func _process(delta):
	# Ensure that Steam.run_callbacks() is being called somewhere in a _process()
	_read_p2p_packet()
```
changed to:
```
func _process(delta):
	# Ensure that Steam.run_callbacks() is being called somewhere in a _process()
	while Steam.getAvailableP2PPacketSize(0) > 0:
		_read_p2p_packet()
```

fixes the issue

**Comment by JDare** [comment]
Sounds good, would you be able to open a PR and I'll get that merged in?

Thanks

**Comment by mtaubert** [comment]
Made a PR with a couple tweaks
